from emkopo_constants.constants import INCOMING, OUTGOING, NEW_LOAN, TOP_UP_LOAN, \
    TAKE_OVER_LOAN, ACCEPT, REJECT, YES, NO, DISBURSED, DISBURSED_EXCEPTION

REQUEST_TYPE = (
    (INCOMING, 'INCOMING'),
    (OUTGOING, 'OUTGOING'),
)

LOAN_TYPE = (
    (NEW_LOAN, 'NEW LOAN'),
    (TOP_UP_LOAN, 'TOP UP LOAN'),
    (TAKE_OVER_LOAN, 'TAKE OVER LOAN'),
)

OFFER_RESPONSE = (
    (ACCEPT, 'ACCEPT'),
    (REJECT, 'REJECT'),
    (DISBURSED, 'DISBURSED'),
    (DISBURSED_EXCEPTION, 'NOT DISBURSED'),
)

YES_NO = (
    (YES, 'Yes'),
    (NO, 'No'),
)
