# Generated by Django 5.1 on 2024-09-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsp",
            name="status",
            field=models.IntegerField(default=1, verbose_name="FSP Status"),
        ),
        migrations.AddField(
            model_name="historicalfsp",
            name="status",
            field=models.IntegerField(default=1, verbose_name="FSP Status"),
        ),
    ]
