# Generated by Django 5.1 on 2024-09-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_product", "0002_fsp_status_historicalfsp_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fsp",
            name="code",
            field=models.CharField(max_length=10, verbose_name="FSP Code"),
        ),
        migrations.AlterField(
            model_name="fsp",
            name="name",
            field=models.CharField(max_length=100, verbose_name="FSP Name"),
        ),
        migrations.AlterField(
            model_name="historicalfsp",
            name="code",
            field=models.CharField(max_length=10, verbose_name="FSP Code"),
        ),
        migrations.AlterField(
            model_name="historicalfsp",
            name="name",
            field=models.CharField(max_length=100, verbose_name="FSP Name"),
        ),
    ]
