# Generated by Django 4.2 on 2024-09-10 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_product", "0006_currency_historicalcurrency"),
    ]

    operations = [
        migrations.AddField(
            model_name="fsp",
            name="sysName",
            field=models.CharField(
                default="FSPSystem", max_length=45, verbose_name="System Name"
            ),
        ),
        migrations.AddField(
            model_name="historicalfsp",
            name="sysName",
            field=models.CharField(
                default="FSPSystem", max_length=45, verbose_name="System Name"
            ),
        ),
    ]
