# Generated by Django 5.1 on 2024-09-17 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_product", "0008_fsp_fspbankaccount_fsp_fspbankaccountname_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalproductcatalog",
            name="Insurance",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Insurance"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproductcatalog",
            name="InterestRate",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Interest Rate"
            ),
        ),
        migrations.AlterField(
            model_name="historicalproductcatalog",
            name="MaximumTenure",
            field=models.IntegerField(verbose_name="Maximum Tenure"),
        ),
        migrations.AlterField(
            model_name="historicalproductcatalog",
            name="MinimumTenure",
            field=models.IntegerField(verbose_name="Minimum Tenure"),
        ),
        migrations.AlterField(
            model_name="historicalproductcatalog",
            name="ProcessFee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Process Fee",
            ),
        ),
        migrations.AlterField(
            model_name="historicalproductcatalog",
            name="RepaymentType",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Repayment Type"
            ),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="Insurance",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Insurance"
            ),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="InterestRate",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Interest Rate"
            ),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="MaximumTenure",
            field=models.IntegerField(verbose_name="Maximum Tenure"),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="MinimumTenure",
            field=models.IntegerField(verbose_name="Minimum Tenure"),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="ProcessFee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=5,
                null=True,
                verbose_name="Process Fee",
            ),
        ),
        migrations.AlterField(
            model_name="productcatalog",
            name="RepaymentType",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Repayment Type"
            ),
        ),
    ]
