# Generated by Django 5.1 on 2024-10-23 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_product", "0010_district_historicalbranch_historicaldistrict_branch"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branch",
            options={
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Branch",
                "verbose_name_plural": "Branches",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalbranch",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Branch",
                "verbose_name_plural": "historical Branches",
            },
        ),
    ]
