# Generated by Django 5.1 on 2024-10-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_product", "0011_alter_branch_options_alter_historicalbranch_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="DistrictNane",
            field=models.CharField(default="", max_length=120, verbose_name="District Name"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaldistrict",
            name="DistrictNane",
            field=models.CharField(default="", max_length=120, verbose_name="District Name"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="district",
            name="DistrictCode",
            field=models.CharField(max_length=45, verbose_name="District Code"),
        ),
        migrations.AlterField(
            model_name="historicaldistrict",
            name="DistrictCode",
            field=models.CharField(max_length=45, verbose_name="District Code"),
        ),
    ]
