from rest_framework import serializers


class LoanOfferRequestSerializer(serializers.Serializer):
    CheckNumber = serializers.IntegerField()
    FirstName = serializers.CharField(max_length=30)
    MiddleName = serializers.CharField(max_length=30, required=False, allow_blank=True)
    LastName = serializers.CharField(max_length=30)
    Sex = serializers.CharField(max_length=1)
    BankAccountNumber = serializers.CharField(max_length=20)
    EmploymentDate = serializers.DateField()
    MaritalStatus = serializers.CharField(max_length=10)
    ConfirmationDate = serializers.CharField(max_length=10)
    TotalEmployeeDeduction = serializers.DecimalField(max_digits=40, decimal_places=2)
    NearestBranchName = serializers.CharField(max_length=50)
    VoteCode = serializers.CharField(max_length=6)
    VoteName = serializers.CharField(max_length=255)
    NIN = serializers.CharField(max_length=22)
    DesignationCode = serializers.CharField(max_length=8)
    DesignationName = serializers.CharField(max_length=255)
    BasicSalary = serializers.DecimalField(max_digits=40, decimal_places=2)
    NetSalary = serializers.DecimalField(max_digits=40, decimal_places=2)
    OneThirdAmount = serializers.DecimalField(max_digits=40, decimal_places=2)
    RequestedAmount = serializers.DecimalField(max_digits=40, decimal_places=2)
    DesiredDeductibleAmount = serializers.DecimalField(max_digits=40, decimal_places=2,
                                                       required=False)
    RetirementDate = serializers.IntegerField()
    TermsOfEmployment = serializers.CharField(max_length=30)
    Tenure = serializers.IntegerField()
    ProductCode = serializers.CharField(max_length=8)
    InterestRate = serializers.DecimalField(max_digits=40, decimal_places=2)
    ProcessingFee = serializers.DecimalField(max_digits=40, decimal_places=2)
    Insurance = serializers.DecimalField(max_digits=40, decimal_places=2)
    PhysicalAddress = serializers.CharField(max_length=50)
    EmailAddress = serializers.CharField(max_length=50)
    MobileNumber = serializers.CharField(max_length=12)
    ApplicationNumber = serializers.CharField(max_length=8)
    LoanPurpose = serializers.CharField(max_length=250)
    ContractStartDate = serializers.DateField()
    ContractEndDate = serializers.DateField()
    Signature = serializers.CharField(max_length=255)
