# Generated by Django 5.1 on 2024-09-13 05:23

import _socket
import django.db.models.deletion
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLoanChargeRequest",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                ("CheckNumber", models.IntegerField(verbose_name="Check number")),
                (
                    "DesignationCode",
                    models.CharField(max_length=8, verbose_name="Designation code"),
                ),
                (
                    "DesignationName",
                    models.CharField(max_length=255, verbose_name="Designation name"),
                ),
                (
                    "BasicSalary",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Basic Salary"
                    ),
                ),
                (
                    "NetSalary",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Net salary"
                    ),
                ),
                (
                    "OneThirdAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="One third amount"
                    ),
                ),
                (
                    "RequestedAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Requested amount",
                    ),
                ),
                (
                    "DeductibleAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Deductible amount"
                    ),
                ),
                (
                    "DesiredDeductibleAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Desired deductible amount",
                    ),
                ),
                ("RetirementDate", models.IntegerField(verbose_name="Retirement date")),
                (
                    "TermsOfEmployment",
                    models.CharField(max_length=30, verbose_name="Terms of employment"),
                ),
                ("Tenure", models.IntegerField(blank=True, null=True, verbose_name="Tenure")),
                ("ProductCode", models.CharField(max_length=8, verbose_name="Product code")),
                ("VoteCode", models.CharField(max_length=10, verbose_name="Vote Code")),
                (
                    "TotalEmployeeDeduction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Total Employee Deduction",
                    ),
                ),
                (
                    "JobClassCode",
                    models.CharField(max_length=10, verbose_name="Job class code"),
                ),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("inward", "INWARD"), ("outward", "OUTWARD")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Loan Charge Request",
                "verbose_name_plural": "historical Loan Charge Requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLoanOfferRequest",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                ("CheckNumber", models.IntegerField(verbose_name="Check number")),
                ("FirstName", models.CharField(max_length=30, verbose_name="First Name")),
                ("MiddleName", models.CharField(max_length=30, verbose_name="Middle Name")),
                ("LastName", models.CharField(max_length=30, verbose_name="Last Name")),
                ("Sex", models.CharField(max_length=1, verbose_name="Sex")),
                (
                    "BankAccountNumber",
                    models.CharField(max_length=20, verbose_name="Bank Account Number"),
                ),
                (
                    "EmploymentDate",
                    models.CharField(max_length=10, verbose_name="Employment Date"),
                ),
                (
                    "MaritalStatus",
                    models.CharField(max_length=10, verbose_name="Marital Status"),
                ),
                (
                    "ConfirmationDate",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Confirmation Date"
                    ),
                ),
                (
                    "TotalEmployeeDeduction",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=40,
                        verbose_name="Total Employee Deduction",
                    ),
                ),
                (
                    "NearestBranchName",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nearest Branch Name",
                    ),
                ),
                ("VoteCode", models.CharField(max_length=6, verbose_name="Vote code")),
                ("VoteName", models.CharField(max_length=255, verbose_name="Vote name")),
                ("NIN", models.CharField(max_length=22, verbose_name="NIN")),
                (
                    "DesignationCode",
                    models.CharField(max_length=8, verbose_name="Designation code"),
                ),
                (
                    "DesignationName",
                    models.CharField(max_length=255, verbose_name="Designation name"),
                ),
                (
                    "BasicSalary",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Basic Salary"
                    ),
                ),
                (
                    "NetSalary",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Net salary"
                    ),
                ),
                (
                    "OneThirdAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="One Third Amount"
                    ),
                ),
                (
                    "RequestedAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Requested amount",
                    ),
                ),
                (
                    "DesiredDeductibleAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Desired deductible amount",
                    ),
                ),
                ("RetirementDate", models.IntegerField(verbose_name="Retirement date")),
                (
                    "TermsOfEmployment",
                    models.CharField(max_length=30, verbose_name="Terms of employment"),
                ),
                ("Tenure", models.IntegerField(verbose_name="Tenure")),
                ("ProductCode", models.CharField(max_length=8, verbose_name="Product code")),
                (
                    "InterestRate",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Interest rate"
                    ),
                ),
                (
                    "ProcessingFee",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Processing fee"
                    ),
                ),
                (
                    "Insurance",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Insurance"
                    ),
                ),
                (
                    "PhysicalAddress",
                    models.CharField(max_length=50, verbose_name="Physical address"),
                ),
                (
                    "TelephoneNumber",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="Telephone number"
                    ),
                ),
                (
                    "EmailAddress",
                    models.CharField(max_length=50, verbose_name="Email address"),
                ),
                (
                    "MobileNumber",
                    models.CharField(max_length=12, verbose_name="Mobile number"),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=8, verbose_name="Application number"),
                ),
                ("LoanPurpose", models.CharField(max_length=250, verbose_name="Loan Purpose")),
                (
                    "ContractStartDate",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Contract Start Date",
                    ),
                ),
                (
                    "ContractEndDate",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Contract End Date"
                    ),
                ),
                (
                    "LoanNumber",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Loan Number"
                    ),
                ),
                (
                    "SettlementAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Settlement amount",
                    ),
                ),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("inward", "INWARD"), ("outward", "OUTWARD")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Loan Offer Request",
                "verbose_name_plural": "historical Loan Offer Requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLoanOfferResponse",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=8, verbose_name="Application number"),
                ),
                (
                    "Reason",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Reason"
                    ),
                ),
                (
                    "FSPReferenceNumber",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="FSP Reference number",
                    ),
                ),
                (
                    "LoanNumber",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Loan Number"
                    ),
                ),
                (
                    "TotalAmountToPay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Total Amount To Pay",
                    ),
                ),
                (
                    "OtherCharges",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Other charges",
                    ),
                ),
                ("Approval", models.CharField(max_length=10, verbose_name="Approval")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("inward", "INWARD"), ("outward", "OUTWARD")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Loan Offer Response",
                "verbose_name_plural": "historical Loan Offer Responses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LoanChargeRequest",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("CheckNumber", models.IntegerField(verbose_name="Check number")),
                (
                    "DesignationCode",
                    models.CharField(max_length=8, verbose_name="Designation code"),
                ),
                (
                    "DesignationName",
                    models.CharField(max_length=255, verbose_name="Designation name"),
                ),
                (
                    "BasicSalary",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Basic Salary"
                    ),
                ),
                (
                    "NetSalary",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Net salary"
                    ),
                ),
                (
                    "OneThirdAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="One third amount"
                    ),
                ),
                (
                    "RequestedAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Requested amount",
                    ),
                ),
                (
                    "DeductibleAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Deductible amount"
                    ),
                ),
                (
                    "DesiredDeductibleAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Desired deductible amount",
                    ),
                ),
                ("RetirementDate", models.IntegerField(verbose_name="Retirement date")),
                (
                    "TermsOfEmployment",
                    models.CharField(max_length=30, verbose_name="Terms of employment"),
                ),
                ("Tenure", models.IntegerField(blank=True, null=True, verbose_name="Tenure")),
                ("ProductCode", models.CharField(max_length=8, verbose_name="Product code")),
                ("VoteCode", models.CharField(max_length=10, verbose_name="Vote Code")),
                (
                    "TotalEmployeeDeduction",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Total Employee Deduction",
                    ),
                ),
                (
                    "JobClassCode",
                    models.CharField(max_length=10, verbose_name="Job class code"),
                ),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("inward", "INWARD"), ("outward", "OUTWARD")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
            ],
            options={
                "verbose_name": "Loan Charge Request",
                "verbose_name_plural": "Loan Charge Requests",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="emkopo_loan_modifie_942a15_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="emkopo_loan_user_mo_57a562_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HistoricalLoanChargeResponse",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "DesiredDeductibleAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Desired deductible amount",
                    ),
                ),
                (
                    "TotalInsurance",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Total Insurance"
                    ),
                ),
                (
                    "TotalProcessingFees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Total Processing Fees",
                    ),
                ),
                (
                    "TotalInterestRateAmount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=40,
                        verbose_name="Total Interest Rate Amount",
                    ),
                ),
                (
                    "OtherCharges",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Other Charges",
                    ),
                ),
                (
                    "NetLoanAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Net Loan Amount"
                    ),
                ),
                (
                    "TotalAmountToPay",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Total Amount To Pay"
                    ),
                ),
                ("Tenure", models.IntegerField(verbose_name="Tenure")),
                (
                    "EligibleAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Eligible Amount",
                    ),
                ),
                (
                    "MonthlyReturnAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Monthly Return Amount"
                    ),
                ),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("inward", "INWARD"), ("outward", "OUTWARD")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "LoanChargeRequest",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="emkopo_loan.loanchargerequest",
                        verbose_name="Loan Charge Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Loan Charge Response",
                "verbose_name_plural": "historical Loan Charge Responses",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LoanOfferRequest",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("CheckNumber", models.IntegerField(verbose_name="Check number")),
                ("FirstName", models.CharField(max_length=30, verbose_name="First Name")),
                ("MiddleName", models.CharField(max_length=30, verbose_name="Middle Name")),
                ("LastName", models.CharField(max_length=30, verbose_name="Last Name")),
                ("Sex", models.CharField(max_length=1, verbose_name="Sex")),
                (
                    "BankAccountNumber",
                    models.CharField(max_length=20, verbose_name="Bank Account Number"),
                ),
                (
                    "EmploymentDate",
                    models.CharField(max_length=10, verbose_name="Employment Date"),
                ),
                (
                    "MaritalStatus",
                    models.CharField(max_length=10, verbose_name="Marital Status"),
                ),
                (
                    "ConfirmationDate",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Confirmation Date"
                    ),
                ),
                (
                    "TotalEmployeeDeduction",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=40,
                        verbose_name="Total Employee Deduction",
                    ),
                ),
                (
                    "NearestBranchName",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Nearest Branch Name",
                    ),
                ),
                ("VoteCode", models.CharField(max_length=6, verbose_name="Vote code")),
                ("VoteName", models.CharField(max_length=255, verbose_name="Vote name")),
                ("NIN", models.CharField(max_length=22, verbose_name="NIN")),
                (
                    "DesignationCode",
                    models.CharField(max_length=8, verbose_name="Designation code"),
                ),
                (
                    "DesignationName",
                    models.CharField(max_length=255, verbose_name="Designation name"),
                ),
                (
                    "BasicSalary",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Basic Salary"
                    ),
                ),
                (
                    "NetSalary",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Net salary"
                    ),
                ),
                (
                    "OneThirdAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="One Third Amount"
                    ),
                ),
                (
                    "RequestedAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Requested amount",
                    ),
                ),
                (
                    "DesiredDeductibleAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Desired deductible amount",
                    ),
                ),
                ("RetirementDate", models.IntegerField(verbose_name="Retirement date")),
                (
                    "TermsOfEmployment",
                    models.CharField(max_length=30, verbose_name="Terms of employment"),
                ),
                ("Tenure", models.IntegerField(verbose_name="Tenure")),
                ("ProductCode", models.CharField(max_length=8, verbose_name="Product code")),
                (
                    "InterestRate",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Interest rate"
                    ),
                ),
                (
                    "ProcessingFee",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Processing fee"
                    ),
                ),
                (
                    "Insurance",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Insurance"
                    ),
                ),
                (
                    "PhysicalAddress",
                    models.CharField(max_length=50, verbose_name="Physical address"),
                ),
                (
                    "TelephoneNumber",
                    models.CharField(
                        blank=True, max_length=12, null=True, verbose_name="Telephone number"
                    ),
                ),
                (
                    "EmailAddress",
                    models.CharField(max_length=50, verbose_name="Email address"),
                ),
                (
                    "MobileNumber",
                    models.CharField(max_length=12, verbose_name="Mobile number"),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=8, verbose_name="Application number"),
                ),
                ("LoanPurpose", models.CharField(max_length=250, verbose_name="Loan Purpose")),
                (
                    "ContractStartDate",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Contract Start Date",
                    ),
                ),
                (
                    "ContractEndDate",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Contract End Date"
                    ),
                ),
                (
                    "LoanNumber",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Loan Number"
                    ),
                ),
                (
                    "SettlementAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Settlement amount",
                    ),
                ),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("inward", "INWARD"), ("outward", "OUTWARD")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
            ],
            options={
                "verbose_name": "Loan Offer Request",
                "verbose_name_plural": "Loan Offer Requests",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="emkopo_loan_modifie_cc08f1_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="emkopo_loan_user_mo_4804bc_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanOfferResponse",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=8, verbose_name="Application number"),
                ),
                (
                    "Reason",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Reason"
                    ),
                ),
                (
                    "FSPReferenceNumber",
                    models.CharField(
                        blank=True,
                        max_length=8,
                        null=True,
                        verbose_name="FSP Reference number",
                    ),
                ),
                (
                    "LoanNumber",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Loan Number"
                    ),
                ),
                (
                    "TotalAmountToPay",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Total Amount To Pay",
                    ),
                ),
                (
                    "OtherCharges",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Other charges",
                    ),
                ),
                ("Approval", models.CharField(max_length=10, verbose_name="Approval")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("inward", "INWARD"), ("outward", "OUTWARD")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
            ],
            options={
                "verbose_name": "Loan Offer Response",
                "verbose_name_plural": "Loan Offer Responses",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="emkopo_loan_modifie_e3a9bf_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="emkopo_loan_user_mo_8b9fd4_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanChargeResponse",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "DesiredDeductibleAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Desired deductible amount",
                    ),
                ),
                (
                    "TotalInsurance",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Total Insurance"
                    ),
                ),
                (
                    "TotalProcessingFees",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Total Processing Fees",
                    ),
                ),
                (
                    "TotalInterestRateAmount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=40,
                        verbose_name="Total Interest Rate Amount",
                    ),
                ),
                (
                    "OtherCharges",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Other Charges",
                    ),
                ),
                (
                    "NetLoanAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Net Loan Amount"
                    ),
                ),
                (
                    "TotalAmountToPay",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Total Amount To Pay"
                    ),
                ),
                ("Tenure", models.IntegerField(verbose_name="Tenure")),
                (
                    "EligibleAmount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=40,
                        null=True,
                        verbose_name="Eligible Amount",
                    ),
                ),
                (
                    "MonthlyReturnAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Monthly Return Amount"
                    ),
                ),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("inward", "INWARD"), ("outward", "OUTWARD")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                (
                    "LoanChargeRequest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loan_charge_responses",
                        to="emkopo_loan.loanchargerequest",
                        verbose_name="Loan Charge Request",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Charge Response",
                "verbose_name_plural": "Loan Charge Responses",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="emkopo_loan_modifie_5a9653_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="emkopo_loan_user_mo_9dd281_idx",
                    ),
                ],
            },
        ),
    ]
