# Generated by Django 5.1 on 2024-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalloanchargerequest",
            name="RequestType",
            field=models.CharField(
                choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                max_length=45,
                verbose_name="Request Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalloanchargeresponse",
            name="RequestType",
            field=models.CharField(
                choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                max_length=45,
                verbose_name="Request Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="RequestType",
            field=models.CharField(
                choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                max_length=45,
                verbose_name="Request Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalloanofferresponse",
            name="RequestType",
            field=models.CharField(
                choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                max_length=45,
                verbose_name="Request Type",
            ),
        ),
        migrations.AlterField(
            model_name="loanchargerequest",
            name="RequestType",
            field=models.CharField(
                choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                max_length=45,
                verbose_name="Request Type",
            ),
        ),
        migrations.AlterField(
            model_name="loanchargeresponse",
            name="RequestType",
            field=models.CharField(
                choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                max_length=45,
                verbose_name="Request Type",
            ),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="RequestType",
            field=models.CharField(
                choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                max_length=45,
                verbose_name="Request Type",
            ),
        ),
        migrations.AlterField(
            model_name="loanofferresponse",
            name="RequestType",
            field=models.CharField(
                choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                max_length=45,
                verbose_name="Request Type",
            ),
        ),
    ]
