# Generated by Django 5.1 on 2024-09-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0004_historicaluserresponse_userresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserresponse",
            name="LoanNumber",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Loan Number"
            ),
        ),
        migrations.AddField(
            model_name="historicaluserresponse",
            name="OtherCharges",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=40,
                null=True,
                verbose_name="Other Charges",
            ),
        ),
        migrations.AddField(
            model_name="historicaluserresponse",
            name="Reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Reason"
            ),
        ),
        migrations.AddField(
            model_name="historicaluserresponse",
            name="TotalAmountToPay",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=40,
                null=True,
                verbose_name="Total Amount to Pay",
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="LoanNumber",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Loan Number"
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="OtherCharges",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=40,
                null=True,
                verbose_name="Other Charges",
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="Reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Reason"
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="TotalAmountToPay",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=40,
                null=True,
                verbose_name="Total Amount to Pay",
            ),
        ),
    ]
