# Generated by Django 5.1 on 2024-09-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0005_historicaluserresponse_loannumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserresponse",
            name="FSPReferenceNumber",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="FSP Reference number"
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="FSPReferenceNumber",
            field=models.CharField(
                blank=True, max_length=8, null=True, verbose_name="FSP Reference number"
            ),
        ),
    ]
