# Generated by Django 5.1 on 2024-09-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0013_historicalloanchargerequest_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserresponse",
            name="ApplicationNumber",
            field=models.CharField(
                default="ESS1678796729374", max_length=45, verbose_name="Application Number"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userresponse",
            name="ApplicationNumber",
            field=models.CharField(
                default="ESS1678796729374", max_length=45, verbose_name="Application Number"
            ),
            preserve_default=False,
        ),
    ]
