# Generated by Django 5.1 on 2024-09-15 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0015_alter_historicaluserresponse_fspresponse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluserresponse",
            name="DisbursementDate",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Disbursement Date"
            ),
        ),
        migrations.AddField(
            model_name="userresponse",
            name="DisbursementDate",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Disbursement Date"
            ),
        ),
    ]
