# Generated by Django 5.1 on 2024-09-15 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0016_historicaluserresponse_disbursementdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalloanofferrequest",
            name="FSPReferenceNumber",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="FSP Reference Number"
            ),
        ),
        migrations.AddField(
            model_name="loanofferrequest",
            name="FSPReferenceNumber",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="FSP Reference Number"
            ),
        ),
    ]
