# Generated by Django 5.1 on 2024-09-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0017_historicalloanofferrequest_fspreferencenumber_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalloanofferrequest",
            name="FailureReason",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Disbursement Failure Reason",
            ),
        ),
        migrations.AddField(
            model_name="historicalloanofferrequest",
            name="Reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Reason"
            ),
        ),
        migrations.AddField(
            model_name="loanofferrequest",
            name="FailureReason",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Disbursement Failure Reason",
            ),
        ),
        migrations.AddField(
            model_name="loanofferrequest",
            name="Reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Reason"
            ),
        ),
    ]
