# Generated by Django 5.1 on 2024-09-16 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0018_historicalloanofferrequest_failurereason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalloanofferrequest",
            name="DisbursementDate",
            field=models.DateField(blank=True, null=True, verbose_name="Disbursement date"),
        ),
        migrations.AddField(
            model_name="historicalloanofferrequest",
            name="TotalAmountToPay",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=40,
                null=True,
                verbose_name="Total Amount to Pay",
            ),
        ),
        migrations.AddField(
            model_name="loanofferrequest",
            name="DisbursementDate",
            field=models.DateField(blank=True, null=True, verbose_name="Disbursement date"),
        ),
        migrations.AddField(
            model_name="loanofferrequest",
            name="TotalAmountToPay",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=40,
                null=True,
                verbose_name="Total Amount to Pay",
            ),
        ),
    ]
