# Generated by Django 5.1 on 2024-09-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0020_alter_historicalloanofferrequest_disbursementdate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalloanofferrequest",
            name="CancellationReason",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Offer Cancellation Reason Reason",
            ),
        ),
        migrations.AddField(
            model_name="loanofferrequest",
            name="CancellationReason",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Offer Cancellation Reason Reason",
            ),
        ),
    ]
