# Generated by Django 5.1 on 2024-09-18 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0025_historicalloantakeoverdetail_loantakeoverdetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalloanofferrequest",
            name="PaymentReferenceNumber",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Payment Reference Number"
            ),
        ),
        migrations.AddField(
            model_name="loanofferrequest",
            name="PaymentReferenceNumber",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Payment Reference Number"
            ),
        ),
    ]
