# Generated by Django 5.1 on 2024-09-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0026_historicalloanofferrequest_paymentreferencenumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="EmailAddress",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="LoanPurpose",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Loan Purpose"
            ),
        ),
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="MobileNumber",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Mobile number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="PhysicalAddress",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Physical address"
            ),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="EmailAddress",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Email address"
            ),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="LoanPurpose",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Loan Purpose"
            ),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="MobileNumber",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Mobile number"
            ),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="PhysicalAddress",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Physical address"
            ),
        ),
    ]
