# Generated by Django 5.1 on 2024-09-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0028_historicalloanofferrequest_fsp1bankaccount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="ApplicationNumber",
            field=models.CharField(max_length=12, verbose_name="Application number"),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="ApplicationNumber",
            field=models.CharField(max_length=12, verbose_name="Application number"),
        ),
    ]
