# Generated by Django 5.1 on 2024-09-25 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0029_alter_historicalloanofferrequest_applicationnumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="RetirementDate",
            field=models.IntegerField(blank=True, null=True, verbose_name="Retirement date"),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="RetirementDate",
            field=models.IntegerField(blank=True, null=True, verbose_name="Retirement date"),
        ),
    ]
