# Generated by Django 5.1 on 2024-09-25 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0030_alter_historicalloanofferrequest_retirementdate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="RetirementDate",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Retirement date"
            ),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="RetirementDate",
            field=models.CharField(
                blank=True, max_length=12, null=True, verbose_name="Retirement date"
            ),
        ),
    ]
