# Generated by Django 5.1 on 2024-09-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0032_alter_historicalloanofferrequest_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="BankAccountNumber",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Bank Account Number"
            ),
        ),
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="EmploymentDate",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Employment Date"
            ),
        ),
        migrations.AlterField(
            model_name="historicalloanofferrequest",
            name="MaritalStatus",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Marital Status"
            ),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="BankAccountNumber",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Bank Account Number"
            ),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="EmploymentDate",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Employment Date"
            ),
        ),
        migrations.AlterField(
            model_name="loanofferrequest",
            name="MaritalStatus",
            field=models.CharField(
                blank=True, max_length=10, null=True, verbose_name="Marital Status"
            ),
        ),
    ]
