# Generated by Django 5.1 on 2024-10-07 20:06

import _socket
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "emkopo_loan",
            "0034_alter_historicalloanofferrequest_totalemployeededuction_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLoanLiquidationRequest",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                ("ProductCode", models.IntegerField(verbose_name="Product Code")),
                (
                    "LoanAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Loan Amount"
                    ),
                ),
                (
                    "DeductionAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Deduction Amount"
                    ),
                ),
                (
                    "TakeOverBalance",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Take Over Balance"
                    ),
                ),
                ("FSP1Code", models.CharField(max_length=45, verbose_name="FSP1 Code")),
                ("FSP1Name", models.CharField(max_length=120, verbose_name="FSP1 Name")),
                (
                    "FSP1LoanNumber",
                    models.CharField(max_length=45, verbose_name="FSP1 Loan Number"),
                ),
                (
                    "FSP1PaymentReferenceNumber",
                    models.CharField(
                        max_length=45, verbose_name="FSP1 Payment Reference Number"
                    ),
                ),
                (
                    "NetLoanAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="NetLoan Amount"
                    ),
                ),
                (
                    "TotalAmountToPay",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Total Amount To Pay"
                    ),
                ),
                ("PaymentRate", models.CharField(max_length=50, verbose_name="Payment Rate")),
                ("Reserved3", models.CharField(max_length=6, verbose_name="Reserved3")),
                (
                    "TermsAndConditionsNumber",
                    models.CharField(
                        max_length=45, verbose_name="Terms And Conditions Number"
                    ),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=45, verbose_name="Application Number"),
                ),
                (
                    "FSPReferenceNumber",
                    models.CharField(max_length=45, verbose_name="FSPReference Number"),
                ),
                (
                    "ApproverName",
                    models.CharField(max_length=45, verbose_name="Approver Name"),
                ),
                (
                    "ApproverDesignation",
                    models.CharField(max_length=60, verbose_name="Approver Designation"),
                ),
                (
                    "ApproverWorkstation",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Approver Workstation",
                    ),
                ),
                (
                    "ApproverInstitution",
                    models.CharField(max_length=255, verbose_name="Approver Institution"),
                ),
                (
                    "ActionDateAndTime",
                    models.DateTimeField(verbose_name="Action Date And Time"),
                ),
                (
                    "ContactPerson",
                    models.CharField(
                        blank=True, max_length=90, null=True, verbose_name="Contact Person"
                    ),
                ),
                (
                    "ApprovalReferenceNumber",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Approval Reference Number",
                    ),
                ),
                ("Status", models.CharField(max_length=30, verbose_name="Status")),
                ("Reason", models.TextField(blank=True, null=True, verbose_name="Reason")),
                ("Comments", models.TextField(blank=True, null=True, verbose_name="Comments")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Loan Liquidation Request",
                "verbose_name_plural": "historical Loan Liquidation Requests",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LoanLiquidationRequest",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ProductCode", models.IntegerField(verbose_name="Product Code")),
                (
                    "LoanAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Loan Amount"
                    ),
                ),
                (
                    "DeductionAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Deduction Amount"
                    ),
                ),
                (
                    "TakeOverBalance",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Take Over Balance"
                    ),
                ),
                ("FSP1Code", models.CharField(max_length=45, verbose_name="FSP1 Code")),
                ("FSP1Name", models.CharField(max_length=120, verbose_name="FSP1 Name")),
                (
                    "FSP1LoanNumber",
                    models.CharField(max_length=45, verbose_name="FSP1 Loan Number"),
                ),
                (
                    "FSP1PaymentReferenceNumber",
                    models.CharField(
                        max_length=45, verbose_name="FSP1 Payment Reference Number"
                    ),
                ),
                (
                    "NetLoanAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="NetLoan Amount"
                    ),
                ),
                (
                    "TotalAmountToPay",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Total Amount To Pay"
                    ),
                ),
                ("PaymentRate", models.CharField(max_length=50, verbose_name="Payment Rate")),
                ("Reserved3", models.CharField(max_length=6, verbose_name="Reserved3")),
                (
                    "TermsAndConditionsNumber",
                    models.CharField(
                        max_length=45, verbose_name="Terms And Conditions Number"
                    ),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=45, verbose_name="Application Number"),
                ),
                (
                    "FSPReferenceNumber",
                    models.CharField(max_length=45, verbose_name="FSPReference Number"),
                ),
                (
                    "ApproverName",
                    models.CharField(max_length=45, verbose_name="Approver Name"),
                ),
                (
                    "ApproverDesignation",
                    models.CharField(max_length=60, verbose_name="Approver Designation"),
                ),
                (
                    "ApproverWorkstation",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Approver Workstation",
                    ),
                ),
                (
                    "ApproverInstitution",
                    models.CharField(max_length=255, verbose_name="Approver Institution"),
                ),
                (
                    "ActionDateAndTime",
                    models.DateTimeField(verbose_name="Action Date And Time"),
                ),
                (
                    "ContactPerson",
                    models.CharField(
                        blank=True, max_length=90, null=True, verbose_name="Contact Person"
                    ),
                ),
                (
                    "ApprovalReferenceNumber",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Approval Reference Number",
                    ),
                ),
                ("Status", models.CharField(max_length=30, verbose_name="Status")),
                ("Reason", models.TextField(blank=True, null=True, verbose_name="Reason")),
                ("Comments", models.TextField(blank=True, null=True, verbose_name="Comments")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Liquidation Request",
                "verbose_name_plural": "Loan Liquidation Requests",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="emkopo_loan_modifie_771b7a_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="emkopo_loan_user_mo_19c1c7_idx",
                    ),
                ],
            },
        ),
    ]
