# Generated by Django 5.1 on 2024-10-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0035_historicalloanliquidationrequest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalloanliquidationrequest",
            name="Reserved3",
            field=models.CharField(max_length=45, verbose_name="Reserved3"),
        ),
        migrations.AlterField(
            model_name="loanliquidationrequest",
            name="Reserved3",
            field=models.CharField(max_length=45, verbose_name="Reserved3"),
        ),
    ]
