# Generated by Django 5.1 on 2024-10-09 06:10

import _socket
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0036_alter_historicalloanliquidationrequest_reserved3_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLoanLiquidationNotification",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "PaymentReference",
                    models.CharField(max_length=45, verbose_name="Payment Reference"),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=60, verbose_name="Application Number"),
                ),
                (
                    "ApproverName",
                    models.CharField(max_length=120, verbose_name="Approver Name"),
                ),
                (
                    "ApproverDesignation",
                    models.CharField(max_length=60, verbose_name="Approver Designation"),
                ),
                (
                    "ApproverWorkstation",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Approver Workstation",
                    ),
                ),
                (
                    "ApproverInstitution",
                    models.CharField(max_length=255, verbose_name="Approver Institution"),
                ),
                (
                    "ActionDateAndTime",
                    models.DateTimeField(verbose_name="Action Date And Time"),
                ),
                (
                    "ContactPerson",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Contact Person"
                    ),
                ),
                (
                    "MonthlyPrincipal",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Monthly Principal"
                    ),
                ),
                (
                    "MonthlyInterest",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Monthly Interest"
                    ),
                ),
                (
                    "MonthlyInstalment",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Monthly Instalment"
                    ),
                ),
                (
                    "OutstandingBalance",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Outstanding Balance"
                    ),
                ),
                (
                    "DeductionStartDate",
                    models.DateTimeField(verbose_name="Deduction Start Date"),
                ),
                (
                    "DeductionEndDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deduction End Date"
                    ),
                ),
                (
                    "FSPReferenceNumber",
                    models.CharField(max_length=45, verbose_name="FSPReferenceNumber"),
                ),
                ("CheckNumber", models.CharField(max_length=45, verbose_name="CheckNumber")),
                ("FirstName", models.CharField(max_length=45, verbose_name="First Name")),
                ("MiddleName", models.CharField(max_length=45, verbose_name="Middle Name")),
                ("LastName", models.CharField(max_length=45, verbose_name="Last Name")),
                ("VoteCode", models.CharField(max_length=45, verbose_name="Vote Code")),
                ("VoteName", models.CharField(max_length=255, verbose_name="Vote Name")),
                ("NIN", models.CharField(max_length=45, verbose_name="NIN")),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Loan Liquidation Notification",
                "verbose_name_plural": "historical Loan Liquidation Notification",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLoanNotificationEmployer",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "PaymentReference",
                    models.CharField(max_length=45, verbose_name="Payment Reference"),
                ),
                ("FSPCode", models.CharField(max_length=45, verbose_name="FSP Code")),
                ("FSPName", models.CharField(max_length=120, verbose_name="FSP Name")),
                ("ProductCode", models.IntegerField(verbose_name="Product Code")),
                ("ProductName", models.CharField(max_length=255, verbose_name="Product Name")),
                (
                    "FSP1LoanNumber",
                    models.CharField(max_length=45, verbose_name="FSP1 Loan Number"),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=45, verbose_name="Application Number"),
                ),
                (
                    "LoanPayoffAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Loan Payoff Amount"
                    ),
                ),
                (
                    "LoanLiquidationDate",
                    models.DateField(verbose_name="Loan Liquidation Date"),
                ),
                ("CheckNumber", models.CharField(max_length=45, verbose_name="Check Number")),
                ("FirstName", models.CharField(max_length=45, verbose_name="First Name")),
                ("MiddleName", models.CharField(max_length=45, verbose_name="Middle Name")),
                ("LastName", models.CharField(max_length=45, verbose_name="Last Name")),
                ("VoteCode", models.CharField(max_length=45, verbose_name="Vote Code")),
                ("VoteName", models.CharField(max_length=45, verbose_name="Vote Name")),
                ("NIN", models.CharField(max_length=45, verbose_name="NIN")),
                (
                    "DeductionCode",
                    models.CharField(max_length=45, verbose_name="Deduction Code"),
                ),
                (
                    "DeductionDescription",
                    models.CharField(max_length=120, verbose_name="Deduction Description"),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Loan Notification Employer",
                "verbose_name_plural": "historical Loan Notification Employer",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLoanTakeoverDisbursementNotification",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=45, verbose_name="Application Number"),
                ),
                (
                    "FSPReferenceNumber",
                    models.CharField(max_length=45, verbose_name="FSPReferenceNumber"),
                ),
                ("LoanNumber", models.CharField(max_length=45, verbose_name="LoanNumber")),
                (
                    "TotalAmountToPay",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Total Amount To Pay"
                    ),
                ),
                ("DisbursementDate", models.DateTimeField(verbose_name="Disbursement Date")),
                ("Reason", models.CharField(max_length=120, verbose_name="Reason")),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Loan Takeover Disbursement Notification",
                "verbose_name_plural": "historical Loan Takeover Disbursement Notification",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LoanLiquidationNotification",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "PaymentReference",
                    models.CharField(max_length=45, verbose_name="Payment Reference"),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=60, verbose_name="Application Number"),
                ),
                (
                    "ApproverName",
                    models.CharField(max_length=120, verbose_name="Approver Name"),
                ),
                (
                    "ApproverDesignation",
                    models.CharField(max_length=60, verbose_name="Approver Designation"),
                ),
                (
                    "ApproverWorkstation",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        null=True,
                        verbose_name="Approver Workstation",
                    ),
                ),
                (
                    "ApproverInstitution",
                    models.CharField(max_length=255, verbose_name="Approver Institution"),
                ),
                (
                    "ActionDateAndTime",
                    models.DateTimeField(verbose_name="Action Date And Time"),
                ),
                (
                    "ContactPerson",
                    models.CharField(
                        blank=True, max_length=60, null=True, verbose_name="Contact Person"
                    ),
                ),
                (
                    "MonthlyPrincipal",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Monthly Principal"
                    ),
                ),
                (
                    "MonthlyInterest",
                    models.DecimalField(
                        decimal_places=2, max_digits=4, verbose_name="Monthly Interest"
                    ),
                ),
                (
                    "MonthlyInstalment",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Monthly Instalment"
                    ),
                ),
                (
                    "OutstandingBalance",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Outstanding Balance"
                    ),
                ),
                (
                    "DeductionStartDate",
                    models.DateTimeField(verbose_name="Deduction Start Date"),
                ),
                (
                    "DeductionEndDate",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Deduction End Date"
                    ),
                ),
                (
                    "FSPReferenceNumber",
                    models.CharField(max_length=45, verbose_name="FSPReferenceNumber"),
                ),
                ("CheckNumber", models.CharField(max_length=45, verbose_name="CheckNumber")),
                ("FirstName", models.CharField(max_length=45, verbose_name="First Name")),
                ("MiddleName", models.CharField(max_length=45, verbose_name="Middle Name")),
                ("LastName", models.CharField(max_length=45, verbose_name="Last Name")),
                ("VoteCode", models.CharField(max_length=45, verbose_name="Vote Code")),
                ("VoteName", models.CharField(max_length=255, verbose_name="Vote Name")),
                ("NIN", models.CharField(max_length=45, verbose_name="NIN")),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Liquidation Notification",
                "verbose_name_plural": "Loan Liquidation Notification",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="emkopo_loan_modifie_c95185_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="emkopo_loan_user_mo_b9c496_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanNotificationEmployer",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "PaymentReference",
                    models.CharField(max_length=45, verbose_name="Payment Reference"),
                ),
                ("FSPCode", models.CharField(max_length=45, verbose_name="FSP Code")),
                ("FSPName", models.CharField(max_length=120, verbose_name="FSP Name")),
                ("ProductCode", models.IntegerField(verbose_name="Product Code")),
                ("ProductName", models.CharField(max_length=255, verbose_name="Product Name")),
                (
                    "FSP1LoanNumber",
                    models.CharField(max_length=45, verbose_name="FSP1 Loan Number"),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=45, verbose_name="Application Number"),
                ),
                (
                    "LoanPayoffAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Loan Payoff Amount"
                    ),
                ),
                (
                    "LoanLiquidationDate",
                    models.DateField(verbose_name="Loan Liquidation Date"),
                ),
                ("CheckNumber", models.CharField(max_length=45, verbose_name="Check Number")),
                ("FirstName", models.CharField(max_length=45, verbose_name="First Name")),
                ("MiddleName", models.CharField(max_length=45, verbose_name="Middle Name")),
                ("LastName", models.CharField(max_length=45, verbose_name="Last Name")),
                ("VoteCode", models.CharField(max_length=45, verbose_name="Vote Code")),
                ("VoteName", models.CharField(max_length=45, verbose_name="Vote Name")),
                ("NIN", models.CharField(max_length=45, verbose_name="NIN")),
                (
                    "DeductionCode",
                    models.CharField(max_length=45, verbose_name="Deduction Code"),
                ),
                (
                    "DeductionDescription",
                    models.CharField(max_length=120, verbose_name="Deduction Description"),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Notification Employer",
                "verbose_name_plural": "Loan Notification Employer",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="emkopo_loan_modifie_1b3c71_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="emkopo_loan_user_mo_066b2f_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanTakeoverDisbursementNotification",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "ApplicationNumber",
                    models.CharField(max_length=45, verbose_name="Application Number"),
                ),
                (
                    "FSPReferenceNumber",
                    models.CharField(max_length=45, verbose_name="FSPReferenceNumber"),
                ),
                ("LoanNumber", models.CharField(max_length=45, verbose_name="LoanNumber")),
                (
                    "TotalAmountToPay",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Total Amount To Pay"
                    ),
                ),
                ("DisbursementDate", models.DateTimeField(verbose_name="Disbursement Date")),
                ("Reason", models.CharField(max_length=120, verbose_name="Reason")),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Takeover Disbursement Notification",
                "verbose_name_plural": "Loan Takeover Disbursement Notification",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="emkopo_loan_modifie_de9b6b_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="emkopo_loan_user_mo_a18843_idx",
                    ),
                ],
            },
        ),
    ]
