# Generated by Django 5.1 on 2024-10-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0040_historicalloanpayoffpaymentresponse_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalloanpayoffpaymentresponse",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Loan Payoff Payment Response",
                "verbose_name_plural": "historical Loan Payoff Payment Response",
            },
        ),
        migrations.AlterModelOptions(
            name="loanpayoffpaymentresponse",
            options={
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "verbose_name": "Loan Payoff Payment Response",
                "verbose_name_plural": "Loan Payoff Payment Response",
            },
        ),
        migrations.AlterField(
            model_name="historicalloanpayoffpaymentresponse",
            name="TotalPayOffAmount",
            field=models.DecimalField(
                decimal_places=2, max_digits=40, verbose_name="Total Pay Off Amount"
            ),
        ),
        migrations.AlterField(
            model_name="loanpayoffpaymentresponse",
            name="TotalPayOffAmount",
            field=models.DecimalField(
                decimal_places=2, max_digits=40, verbose_name="Total Pay Off Amount"
            ),
        ),
    ]
