# Generated by Django 5.1 on 2024-10-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0042_fullloanrepaymentnotification_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fullloanrepaymentnotification",
            name="ApplicationNumber",
            field=models.CharField(max_length=45, verbose_name="Application Number"),
        ),
        migrations.AlterField(
            model_name="fullloanrepaymentnotification",
            name="DeductionCode",
            field=models.CharField(max_length=45, verbose_name="Deduction Code"),
        ),
        migrations.AlterField(
            model_name="fullloanrepaymentnotification",
            name="LoanNumber",
            field=models.CharField(max_length=45, verbose_name="Loan Number"),
        ),
        migrations.AlterField(
            model_name="fullloanrepaymentnotification",
            name="PaymentReference",
            field=models.CharField(max_length=45, verbose_name="Payment Reference"),
        ),
        migrations.AlterField(
            model_name="historicalfullloanrepaymentnotification",
            name="ApplicationNumber",
            field=models.CharField(max_length=45, verbose_name="Application Number"),
        ),
        migrations.AlterField(
            model_name="historicalfullloanrepaymentnotification",
            name="DeductionCode",
            field=models.CharField(max_length=45, verbose_name="Deduction Code"),
        ),
        migrations.AlterField(
            model_name="historicalfullloanrepaymentnotification",
            name="LoanNumber",
            field=models.CharField(max_length=45, verbose_name="Loan Number"),
        ),
        migrations.AlterField(
            model_name="historicalfullloanrepaymentnotification",
            name="PaymentReference",
            field=models.CharField(max_length=45, verbose_name="Payment Reference"),
        ),
    ]
