# Generated by Django 5.1 on 2024-10-20 18:03

import _socket
import django.db.models.deletion
import django.utils.timezone
import django_audit_fields.fields.hostname_modification_field
import django_audit_fields.fields.userfield
import django_audit_fields.fields.uuid_auto_field
import django_audit_fields.models.audit_model_mixin
import django_revision.revision_field
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0049_accountvalidationrequest_accountvalidationresponse_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalLoanDeductionRecord",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                ("LoanNumber", models.CharField(max_length=20, verbose_name="Loan Number")),
                ("CheckNumber", models.IntegerField(verbose_name="Check number")),
                ("FirstName", models.CharField(max_length=30, verbose_name="First Name")),
                ("MiddleName", models.CharField(max_length=30, verbose_name="Middle Name")),
                ("LastName", models.CharField(max_length=30, verbose_name="Last Name")),
                ("NationalId", models.CharField(max_length=45, verbose_name="National ID")),
                ("VoteCode", models.CharField(max_length=6, verbose_name="Vote code")),
                ("VoteName", models.CharField(max_length=255, verbose_name="Vote name")),
                (
                    "DepartmentCode",
                    models.CharField(max_length=45, verbose_name="Department Code"),
                ),
                (
                    "DepartmentName",
                    models.CharField(max_length=45, verbose_name="Department Name"),
                ),
                (
                    "DeductionCode",
                    models.CharField(max_length=45, verbose_name="Deduction Code"),
                ),
                (
                    "DeductionDescription",
                    models.CharField(max_length=120, verbose_name="Deduction Description"),
                ),
                (
                    "BalanceAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Balance Amount"
                    ),
                ),
                (
                    "DeductionAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Deduction Amount"
                    ),
                ),
                ("HasStopPay", models.BooleanField(verbose_name="Has stop pay")),
                (
                    "StopPayReason",
                    models.CharField(max_length=255, verbose_name="Stop pay reason"),
                ),
                ("CheckDate", models.DateField(verbose_name="Check date")),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Loan Deduction Record",
                "verbose_name_plural": "historical Loan Deduction Records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalLoanDeductionStopNotification",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        db_index=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                    ),
                ),
                (
                    "FSPReferenceNumber",
                    models.CharField(max_length=45, verbose_name="FSP Reference Number"),
                ),
                ("LoanNumber", models.CharField(max_length=20, verbose_name="Loan Number")),
                ("CheckNumber", models.IntegerField(verbose_name="Check number")),
                ("FirstName", models.CharField(max_length=30, verbose_name="First Name")),
                ("MiddleName", models.CharField(max_length=30, verbose_name="Middle Name")),
                ("LastName", models.CharField(max_length=30, verbose_name="Last Name")),
                ("NationalId", models.CharField(max_length=45, verbose_name="National ID")),
                ("VoteCode", models.CharField(max_length=6, verbose_name="Vote code")),
                ("VoteName", models.CharField(max_length=255, verbose_name="Vote name")),
                (
                    "DepartmentCode",
                    models.CharField(max_length=45, verbose_name="Department Code"),
                ),
                (
                    "DepartmentName",
                    models.CharField(max_length=45, verbose_name="Department Name"),
                ),
                (
                    "DeductionCode",
                    models.CharField(max_length=45, verbose_name="Deduction Code"),
                ),
                (
                    "DeductionDescription",
                    models.CharField(max_length=120, verbose_name="Deduction Description"),
                ),
                (
                    "BalanceAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Balance Amount"
                    ),
                ),
                (
                    "DeductionAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Deduction Amount"
                    ),
                ),
                ("StopDate", models.DateField(verbose_name="Stop Date")),
                (
                    "StopPayReason",
                    models.CharField(max_length=255, verbose_name="Stop pay reason"),
                ),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Loan Deduction Stop Notification",
                "verbose_name_plural": "historical Loan Deduction Stop Notifications",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="LoanDeductionRecord",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("LoanNumber", models.CharField(max_length=20, verbose_name="Loan Number")),
                ("CheckNumber", models.IntegerField(verbose_name="Check number")),
                ("FirstName", models.CharField(max_length=30, verbose_name="First Name")),
                ("MiddleName", models.CharField(max_length=30, verbose_name="Middle Name")),
                ("LastName", models.CharField(max_length=30, verbose_name="Last Name")),
                ("NationalId", models.CharField(max_length=45, verbose_name="National ID")),
                ("VoteCode", models.CharField(max_length=6, verbose_name="Vote code")),
                ("VoteName", models.CharField(max_length=255, verbose_name="Vote name")),
                (
                    "DepartmentCode",
                    models.CharField(max_length=45, verbose_name="Department Code"),
                ),
                (
                    "DepartmentName",
                    models.CharField(max_length=45, verbose_name="Department Name"),
                ),
                (
                    "DeductionCode",
                    models.CharField(max_length=45, verbose_name="Deduction Code"),
                ),
                (
                    "DeductionDescription",
                    models.CharField(max_length=120, verbose_name="Deduction Description"),
                ),
                (
                    "BalanceAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Balance Amount"
                    ),
                ),
                (
                    "DeductionAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Deduction Amount"
                    ),
                ),
                ("HasStopPay", models.BooleanField(verbose_name="Has stop pay")),
                (
                    "StopPayReason",
                    models.CharField(max_length=255, verbose_name="Stop pay reason"),
                ),
                ("CheckDate", models.DateField(verbose_name="Check date")),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Deduction Record",
                "verbose_name_plural": "Loan Deduction Records",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="emkopo_loan_modifie_c16fc2_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="emkopo_loan_user_mo_405a53_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LoanDeductionStopNotification",
            fields=[
                (
                    "revision",
                    django_revision.revision_field.RevisionField(
                        blank=True,
                        editable=False,
                        help_text="System field. Git repository tag:branch:commit.",
                        max_length=75,
                        null=True,
                        verbose_name="Revision",
                    ),
                ),
                (
                    "created",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "modified",
                    models.DateTimeField(
                        blank=True, default=django_audit_fields.models.audit_model_mixin.utcnow
                    ),
                ),
                (
                    "user_created",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user created",
                    ),
                ),
                (
                    "user_modified",
                    django_audit_fields.fields.userfield.UserField(
                        blank=True,
                        help_text="Updated by admin.save_model",
                        max_length=50,
                        verbose_name="user modified",
                    ),
                ),
                (
                    "hostname_created",
                    models.CharField(
                        blank=True,
                        default=_socket.gethostname,
                        help_text="System field. (modified on create only)",
                        max_length=60,
                        verbose_name="Hostname created",
                    ),
                ),
                (
                    "hostname_modified",
                    django_audit_fields.fields.hostname_modification_field.HostnameModificationField(
                        blank=True,
                        help_text="System field. (modified on every save)",
                        max_length=50,
                        verbose_name="Hostname modified",
                    ),
                ),
                (
                    "device_created",
                    models.CharField(blank=True, max_length=10, verbose_name="Device created"),
                ),
                (
                    "device_modified",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Device modified"
                    ),
                ),
                (
                    "locale_created",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale created",
                    ),
                ),
                (
                    "locale_modified",
                    models.CharField(
                        blank=True,
                        help_text="Auto-updated by Modeladmin",
                        max_length=10,
                        null=True,
                        verbose_name="Locale modified",
                    ),
                ),
                (
                    "id",
                    django_audit_fields.fields.uuid_auto_field.UUIDAutoField(
                        blank=True,
                        editable=False,
                        help_text="System auto field. UUID primary key.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "FSPReferenceNumber",
                    models.CharField(max_length=45, verbose_name="FSP Reference Number"),
                ),
                ("LoanNumber", models.CharField(max_length=20, verbose_name="Loan Number")),
                ("CheckNumber", models.IntegerField(verbose_name="Check number")),
                ("FirstName", models.CharField(max_length=30, verbose_name="First Name")),
                ("MiddleName", models.CharField(max_length=30, verbose_name="Middle Name")),
                ("LastName", models.CharField(max_length=30, verbose_name="Last Name")),
                ("NationalId", models.CharField(max_length=45, verbose_name="National ID")),
                ("VoteCode", models.CharField(max_length=6, verbose_name="Vote code")),
                ("VoteName", models.CharField(max_length=255, verbose_name="Vote name")),
                (
                    "DepartmentCode",
                    models.CharField(max_length=45, verbose_name="Department Code"),
                ),
                (
                    "DepartmentName",
                    models.CharField(max_length=45, verbose_name="Department Name"),
                ),
                (
                    "DeductionCode",
                    models.CharField(max_length=45, verbose_name="Deduction Code"),
                ),
                (
                    "DeductionDescription",
                    models.CharField(max_length=120, verbose_name="Deduction Description"),
                ),
                (
                    "BalanceAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Balance Amount"
                    ),
                ),
                (
                    "DeductionAmount",
                    models.DecimalField(
                        decimal_places=2, max_digits=40, verbose_name="Deduction Amount"
                    ),
                ),
                ("StopDate", models.DateField(verbose_name="Stop Date")),
                (
                    "StopPayReason",
                    models.CharField(max_length=255, verbose_name="Stop pay reason"),
                ),
                (
                    "Timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Timestamp"
                    ),
                ),
                ("status", models.IntegerField(default=1, verbose_name="Status")),
                ("MessageType", models.CharField(max_length=100, verbose_name="Message Type")),
                (
                    "RequestType",
                    models.CharField(
                        choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                        max_length=45,
                        verbose_name="Request Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Loan Deduction Stop Notification",
                "verbose_name_plural": "Loan Deduction Stop Notifications",
                "abstract": False,
                "default_permissions": ("add", "change", "delete", "view", "export", "import"),
                "indexes": [
                    models.Index(
                        fields=["modified", "created"], name="emkopo_loan_modifie_ec70d4_idx"
                    ),
                    models.Index(
                        fields=["user_modified", "user_created"],
                        name="emkopo_loan_user_mo_b969ea_idx",
                    ),
                ],
            },
        ),
    ]
