# Generated by Django 5.1 on 2024-10-22 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0050_historicalloandeductionrecord_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalloandefaulterdetail",
            name="EmploymentStatus",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Employment Status"
            ),
        ),
        migrations.AlterField(
            model_name="historicalloandefaulterdetail",
            name="PhysicalAddress",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Physical Address"
            ),
        ),
        migrations.AlterField(
            model_name="historicalloandefaulterdetail",
            name="TelephoneNumber",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Telephone Number"
            ),
        ),
        migrations.AlterField(
            model_name="loandefaulterdetail",
            name="EmploymentStatus",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Employment Status"
            ),
        ),
        migrations.AlterField(
            model_name="loandefaulterdetail",
            name="PhysicalAddress",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Physical Address"
            ),
        ),
        migrations.AlterField(
            model_name="loandefaulterdetail",
            name="TelephoneNumber",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Telephone Number"
            ),
        ),
    ]
