# Generated by Django 5.1 on 2024-10-22 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0051_alter_historicalloandefaulterdetail_employmentstatus_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalloandefaulterdetail",
            name="Institution",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Institution"
            ),
        ),
        migrations.AddField(
            model_name="loandefaulterdetail",
            name="Institution",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Institution"
            ),
        ),
    ]
