# Generated by Django 5.1 on 2024-10-23 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0052_historicalloandefaulterdetail_institution_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountvalidationresponse",
            name="AccountNumber",
            field=models.CharField(default="", max_length=45, verbose_name="Account Number"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalaccountvalidationresponse",
            name="AccountNumber",
            field=models.CharField(default="", max_length=45, verbose_name="Account Number"),
            preserve_default=False,
        ),
    ]
