# Generated by Django 5.1 on 2024-10-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0053_accountvalidationresponse_accountnumber_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalloandeductionrecord",
            name="HasStopPay",
            field=models.BooleanField(blank=True, null=True, verbose_name="Has stop pay"),
        ),
        migrations.AlterField(
            model_name="historicalloandeductionrecord",
            name="StopPayReason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stop pay reason"
            ),
        ),
        migrations.AlterField(
            model_name="loandeductionrecord",
            name="HasStopPay",
            field=models.BooleanField(blank=True, null=True, verbose_name="Has stop pay"),
        ),
        migrations.AlterField(
            model_name="loandeductionrecord",
            name="StopPayReason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stop pay reason"
            ),
        ),
    ]
