# Generated by Django 5.1 on 2024-10-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_loan", "0054_alter_historicalloandeductionrecord_hasstoppay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalloandeductionstopnotification",
            name="StopReason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stop Reason"
            ),
        ),
        migrations.AddField(
            model_name="loandeductionstopnotification",
            name="StopReason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stop Reason"
            ),
        ),
        migrations.AlterField(
            model_name="historicalloandeductionstopnotification",
            name="StopPayReason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stop pay reason"
            ),
        ),
        migrations.AlterField(
            model_name="loandeductionstopnotification",
            name="StopPayReason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Stop pay reason"
            ),
        ),
    ]
