# Generated by Django 4.2.15 on 2024-09-11 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_api", "0002_apirequest_apiurl_historicalapirequest_apiurl"),
    ]

    operations = [
        migrations.RenameField(
            model_name="apirequest",
            old_name="RequestType",
            new_name="RequestKind",
        ),
        migrations.RenameField(
            model_name="historicalapirequest",
            old_name="RequestType",
            new_name="RequestKind",
        ),
    ]
