# Generated by Django 5.1 on 2024-09-13 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_api", "0004_remove_apirequest_requestkind_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apirequest",
            name="RequestType",
            field=models.CharField(
                choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                max_length=45,
                verbose_name="Request Type",
            ),
        ),
        migrations.AlterField(
            model_name="historicalapirequest",
            name="RequestType",
            field=models.CharField(
                choices=[("incoming", "INCOMING"), ("outgoing", "OUTGOING")],
                max_length=45,
                verbose_name="Request Type",
            ),
        ),
    ]
