# Generated by Django 5.1 on 2024-10-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emkopo_api", "0005_alter_apirequest_requesttype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="apirequest",
            name="response",
            field=models.TextField(blank=True, null=True, verbose_name="Response"),
        ),
        migrations.AddField(
            model_name="historicalapirequest",
            name="response",
            field=models.TextField(blank=True, null=True, verbose_name="Response"),
        ),
    ]
