from .produuct_catalog import ProductCatalogXMLView
from .product_decommission import GenerateXMLForDecommissionView
from .loan_charge_request import LoanChargesRequestAPIView
from .loan_offer_request import LoanOfferRequestAPIView
from .loan_offer_response import LoanOfferResponseAPIView
from .loan_final_appproval import LoanFinalApprovalNotificationAPIView
from .disbursement_notification import LoanDisbursementNotificationAPIView
from .fail_disbursement import LoanDisbursementFailureNotificationAPIView
from .offer_cancellation import LoanOfferCancellationNotificationAPIView
from .payoff_balance_request import LoanPayOffBalanceRequestAPIView
from .settlement_balance_response import LoanSettlementBalanceResponseAPIView
from .loan_restructuring import LoanRestructuringRequestAPIView
from .loan_takeover_details import LoanTakeOverDetailsAPIView
from .loan_liquidation_request import LoanLiquidationRequestAPIView
from .loan_notification_employer import LoanNotificationToEmployerAPIView
from .loan_liquidation_notification import LoanLiquidationNotificationAPIView
from .loan_takeover_disb_notification import LoanTakeoverDisbursementNotificationAPIView
from .loan_repayment_request import LoanRepaymentRequestAPIView
from .repayment_offbalance_request import LoanRepaymentOffBalanceRequestAPIView
from .payoff_payment_response import LoanPayoffPaymentResponseAPIView
from .full_loan_repayment_notification import FullLoanRepaymentNotificationAPIView





