from .constants import (
    STAFF_ROLE,
    EMKOPO_SUPER_ADMIN_ROLE,
    EMKOPO_USER_ROLE,
    EMKOPO_ADMIN_ROLE,
    EMKOPO_OPERATOR_ROLE,
    AUDITOR_ROLE,

)
from .group_names import (
    EVERYONE,
    EMKOPO_SUPER_ADMIN,
    EMKOPO_ADMIN,
    EMKOPO_USER,
    EMKOPO_OPERATOR,
    AUDITOR,
)

role_names = {
    EMKOPO_SUPER_ADMIN_ROLE: "EMKOPO SUPER ADMIN",
    EMKOPO_ADMIN_ROLE: "EMKOPO ADMIN",
    EMKOPO_USER_ROLE: "EMKOPO USER",
    EMKOPO_OPERATOR_ROLE: "EMKOPO OPERATOR",
    STAFF_ROLE: "Staff",
    AUDITOR_ROLE: "AUDITOR",
}

required_role_names = {STAFF_ROLE: "Staff"}

groups_by_role_name = {
    AUDITOR_ROLE: [AUDITOR, EVERYONE],
    EMKOPO_SUPER_ADMIN_ROLE: [EMKOPO_SUPER_ADMIN, EMKOPO_USER, EMKOPO_OPERATOR, EVERYONE],
    EMKOPO_ADMIN_ROLE: [EMKOPO_ADMIN, EVERYONE],
    EMKOPO_USER_ROLE: [EMKOPO_USER, EVERYONE],
    STAFF_ROLE: [EVERYONE],
    EMKOPO_OPERATOR_ROLE: [EMKOPO_OPERATOR, EVERYONE],
}
